{{- if and .Values.global.ingress.enabled .Values.global.registry.internal }}
apiVersion: {{ include "docker-registry.ingress.apiVersion" . }}
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: {{ .Values.global.ingress.issuer | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: {{ .Release.Name }}-registry-ingress
spec:
  rules:
  - host: {{ .Values.global.registry.url }}
    http:
      paths:
      - backend:
          serviceName: {{ template "docker-registry.fullname" . }}
          servicePort: 5000
        path: /
  tls:
  - hosts:
    - {{ .Values.global.registry.url }}
    secretName: {{ .Release.Name }}-registry-tls
{{- end -}}
