{{- if .Values.global.registry.ingress.enabled }}
apiVersion: {{ include "docker-registry.ingress.apiVersion" . }}
kind: Ingress
metadata:
  labels:
    app: {{ include "docker-registry.name" . }}
    chart: {{ include "docker-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: {{ .Values.global.registry.ingress.issuer | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: {{ .Release.Name }}-registry-ingress
spec:
  rules:
  - host: {{ .Values.global.registry.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ include "docker-registry.fullname" . }}
          servicePort: 5000
        path: {{ .Values.global.registry.ingress.path }}
  tls:
  - hosts:
    - {{ .Values.global.registry.ingress.host }}
    secretName: {{ .Release.Name }}-registry-tls
{{- end -}}
