{{- if eq .Values.global.registry.url "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-docker-registry-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "docker-registry.name" . }}
    chart: {{ include "docker-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.global.registry.password | b64enc | quote }}
  storageInit: {{ include "docker-registry.storageInit" . | b64enc | quote }}
{{- end }}