rootcause:
    - '((?-i)rootcause)'
manager:
    - '((?-i)manager)'
sonar:
    - '((?-i)sonar)'
gateway:
    - '((?-i)gateway)'
autood:
    - '((?-i)autood)'
visualization:
    - '((?-i)visualization)'
ui:
    - '((?-i)ui)'
sdk:
    - '((?-i)sdk)'
protos:
    - '((?-i)protos)'
example:
    - '((?-i)example)'