global:
  url: "" # Prometheus AlertManager address in case you want to use the external installation.
            # If empty, an internal installation will be deployed.
  config:
    global: 
      smtp_smarthost: localhost:25 # SMTP relay host
      smtp_auth_username: mailbot # SMTP relay username 
      smtp_auth_identity: mailbot # SMTP relay username identity
      smtp_auth_password: mailbot # SMTP relay password
      smtp_from: no-reply@hydrosphere.io # Email address of the sender
    route:
      group_by: [alertname, modelVersionId]
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: default
    receivers:
    - name: default
      email_configs: # List of email addresses to send alarms to
      - to: customer@example.io 

  tolerations: []

image:
  repository: prom/alertmanager
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

config: {}


service:
  type: ClusterIP
  port: 9093

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}