apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ui.fullname" . | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "ui.name" . }}
    chart: {{ include "ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.json: |-
{{ .Values.global.ui.configuration | indent 4 }}