ui:
  image:
    full: hydrosphere/hydro-serving-ui:3787d1f41444c7950e0dad24a5fef26e840b4232
manager:
  image:
    full: hydrosphere/serving-manager:2c78143afe33023f1f0e022408c4232d2d384c0f
  depconfig: |-
    default-deployment-configuration = """
      {
        "name":"default",
        "hpa":{
            "minReplicas":1,
            "maxReplicas":10,
            "cpuUtilization":80
        },
        "pod":{
          "tolerations":[{
                "key":"node-type",
                "operator":"Equal",
                "value":"hydrosphere.io",
                "effect":"NoSchedule"
          }]
        }
      }
    """
gateway:
  image:
    full: hydrosphere/serving-gateway:baf1199aee714385e635dbfaee49e58954048da3
sonar:
  image:
    full: hydrosphere/sonar:495830e0910b65420c79e307d3b9df7f1a87917b
visualization:
  image:
    full: hydrosphere/hydro-visualization:94f27b119de749cc646d9faa3bedb83160d25002
auto-od:
  image:
    full: hydrosphere/auto-od:d9b5700c61844a9748da1d847518e6de367a0309
stat:
  image:
    full: hydrosphere/stat:5b5bc87c010abbd0787b234c3e195564ce31c6b6
rootcause:
  image:
    full: hydrosphere/hydro-root-cause:1d3495440b803fee80cdaa20707ae1d84a3796c7
global:
  tolerations:
  - key: "node-type"
    operator: "Equal"
    value: "hydrosphere.io"
    effect: "NoSchedule"