ui:
  image:
    full: hydrosphere/hydro-serving-ui:a3e00f1a7eaae8e8ca58936b144fdb98ca34f9f0
manager:
  image:
    full: hydrosphere/serving-manager:1f73a2ad9a86c0a67847cd8f004e5c5e2ac331d1
  depconfig: |-
    default-deployment-configuration = """
      {
        "name":"default",
        "hpa":{
            "minReplicas":1,
            "maxReplicas":10,
            "cpuUtilization":80
        },
        "pod":{
          "tolerations":[{
                "key":"node-type",
                "operator":"Equal",
                "value":"dev",
                "effect":"NoSchedule"
          }]
        }
      }
    """
gateway:
  image:
    full: hydrosphere/serving-gateway:e28788006e0cbf7d9bfa3ca6c0c9779a6f322220
sonar:
  image:
    full: hydrosphere/sonar:495830e0910b65420c79e307d3b9df7f1a87917b
visualization:
  image:
    full: hydrosphere/hydro-visualization:b498e987681e5b8c71e7e9e0fe687e1d8673b50c
auto-od:
  image:
    full: hydrosphere/auto-od:d9b5700c61844a9748da1d847518e6de367a0309
stat:
  image:
    full: hydrosphere/stat:5b5bc87c010abbd0787b234c3e195564ce31c6b6
rootcause:
  image:
    full: hydrosphere/hydro-root-cause:2422bedda3ee2d00f8e0be2fcf6e5a739a397cbf
postgresql:
  metrics:
    enabled: true
  serviceMonitor:
    enabled: true
global:
  ui:
    ingress:
      enabled: true
      host: "hydro-serving.dev.hydrosphere.io"
      grpchost: "hydro-grpc.dev.hydrosphere.io"
  registry:
    insecure: false
    ingress:
      enabled: true
      host: "hydro-registry.dev.hydrosphere.io"
  persistence:
    url: ""
    mode: "minio"
    region: "us-west-1" # region for s3

  tolerations:
  - key: "node-type"
    operator: "Equal"
    value: "hydrosphere.io"
    effect: "NoSchedule"