ui:
  image:
    full: hydrosphere/serving-ui:eba6295a96703e940a7c946c4961e2ec740011f4
manager:
  image:
    full: hydrosphere/serving-manager:d27118a51151e2b6b0df748a2d6bcb3d20d19027
gateway:
  image:
    full: harbor.hydrosphere.io/hydro-serving/hydro-serving-gateway:latest