ui:
  image:
    full: harbor.hydrosphere.io/hydro-serving/hydro-serving-ui:latest
manager:
  image:
    full: hydrosphere/serving-manager:5b698efff60c8852749c9fb2c0f7b2848da55bd5
gateway:
  image:
    full: harbor.hydrosphere.io/hydro-serving/hydro-serving-gateway:latest