ui:
  image:
    full: hydrosphere/hydro-serving-ui:2aa6c4c08b8709c1d71b7a410d37363cfe494143
manager:
  image:
    full: hydrosphere/serving-manager:bf6e2b74633c91ca66858e05e186fee895e00653
gateway:
  image:
    full: hydrosphere/serving-gateway:98e9add3a034ef5b85d628bb17cbceec1bfd515c
sonar:
  image:
    full: hydrosphere/sonar:495830e0910b65420c79e307d3b9df7f1a87917b
visualization:
  image:
    full: hydrosphere/hydro-visualization:fa9ff705deb7192baa984569505c5cc6b8151de9  
auto-od:
  image:
    full: hydrosphere/auto-od:d9b5700c61844a9748da1d847518e6de367a0309
stat:
  image:
    full: hydrosphere/stat:5b5bc87c010abbd0787b234c3e195564ce31c6b6
rootcause:
  image:
    full: hydrosphere/hydro-root-cause:1d3495440b803fee80cdaa20707ae1d84a3796c7
global:
  tolerations:
  - key: "node-type"
    operator: "Equal"
    value: "hydrosphere.io"
    effect: "NoSchedule"