ui:
  image:
    full: bulbawarrior/hydro-serving-ui:4.6.0
manager:
  image:
    full: bulbawarrior/serving-manager:6b78e38444449128dda2f809717ee6332d6eb092
  depconfig: |-
    default-deployment-configuration = """
      {
        "name":"default",
        "hpa":{
            "minReplicas":1,
            "maxReplicas":10,
            "cpuUtilization":80
        },
        "pod":{
          "tolerations":[{
                "key":"node-type",
                "operator":"Equal",
                "value":"dev",
                "effect":"NoSchedule"
          }]
        }
      }
    """
gateway:
  image:
    full: bulbawarrior/serving-gateway:98a4c29c349ebcef6ff7ad5f13fae11144bcc8f4
    full: bulbawarrior/sonar:4.6.0
  image:
    full: bulbawarrior/sonar:4.6.0
visualization:
  image:
    full: bulbawarrior/hydro-visualization:4.6.0
auto-od:
  image:
    full: hydrosphere/auto-od:d9b5700c61844a9748da1d847518e6de367a0309
    full: bulbawarrior/stat:4.6.0
  image:
    full: bulbawarrior/stat:4.6.0
rootcause:
  image:
    full: bulbawarrior/hydro-root-cause:4.6.0
postgresql:
  metrics:
    enabled: true
  serviceMonitor:
    enabled: true
global:
  ui:
    ingress:
      enabled: true
      host: "hydro-serving.dev.hydrosphere.io"
      grpchost: "hydro-grpc.dev.hydrosphere.io"
  registry:
    insecure: false
    ingress:
      enabled: true
      host: "hydro-registry.dev.hydrosphere.io"
  persistence:
    url: ""
    mode: "minio"
    region: "us-west-1" # region for s3

  tolerations:
  - key: "node-type"
    operator: "Equal"
    value: "hydrosphere.io"
    effect: "NoSchedule"
