ui:
  image:
    full: harbor.hydrosphere.io/hydro-serving/hydro-serving-ui:latest
manager:
  image:
    full: hydrosphere/serving-manager:9b3e70a5573fcab953f558d45c2a930876a33434
gateway:
  image:
    full: harbor.hydrosphere.io/hydro-serving/hydro-serving-gateway:latest