ui:
  image:
    full: hydrosphere/hydro-serving-ui:ad93037e196daa7dacb4e3abb17cbb09629083bc
manager:
  image:
    full: hydrosphere/serving-manager:bb7f77f99ce214d57ead3b719acedda94db56b04
gateway:
  image:
    full: hydrosphere/serving-gateway:933ed22f29815c126c312cd484cc3bff0c4c9eef
sonar:
  image:
    full: hydrosphere/sonar:d4da8f3510a9594bd883deceb18892bfc73e097c
visualization:
  image:
    full: hydrosphere/hydro-visualization:fa9ff705deb7192baa984569505c5cc6b8151de9  
    full: hydrosphere/auto-od:d4e1a2e9cbb869ea77ecb3b22c7c17796adfe4bb
  image:
    full: hydrosphere/auto-od:d4e1a2e9cbb869ea77ecb3b22c7c17796adfe4bb
stat:
  image:
    full: hydrosphere/stat:f72b0ceb5911bd249455e6cb7ae0d2e9d412cf1c
rootcause:
  image:
    full: hydrosphere/hydro-root-cause:73721910db505b35226249756bdfe3b475f97497
