ui:
  image:
    full: hydrosphere/hydro-serving-ui:1db6889e72d0a7afe2142ccf3ef4ab6462d495c5
manager:
  image:
    full: hydrosphere/serving-manager:8b2ad5140ee2960e145463b9f1a8bad258c7f50a
  depconfig: |-
    default-deployment-configuration = """
      {
        "name":"default",
        "hpa":{
            "minReplicas":1,
            "maxReplicas":10,
            "cpuUtilization":80
        },
        "pod":{
          "tolerations":[{
                "key":"node-type",
                "operator":"Equal",
                "value":"dev",
                "effect":"NoSchedule"
          }]
        }
      }
    """
gateway:
  image:
    full: hydrosphere/serving-gateway:0e20cb4257be274948ae068381c20fda5a556b85
sonar:
  image:
    full: hydrosphere/sonar:12ff938de71d8bafac4916383ce8ceeb2023f390
visualization:
  image:
    full: bulbawarrior/hydro-visualization:4.5.0
auto-od:
  image:
    full: hydrosphere/auto-od:d9b5700c61844a9748da1d847518e6de367a0309
    full: bulbawarrior/stat:4.5.0
  image:
    full: bulbawarrior/stat:4.5.0
rootcause:
  image:
    full: hydrosphere/hydro-root-cause:fd53787e458648a32d6d01d57c21e8afe50c8e19
postgresql:
  metrics:
    enabled: true
  serviceMonitor:
    enabled: true
global:
  ui:
    ingress:
      enabled: true
      host: "hydro-serving.dev.hydrosphere.io"
      grpchost: "hydro-grpc.dev.hydrosphere.io"
  registry:
    insecure: false
    ingress:
      enabled: true
      host: "hydro-registry.dev.hydrosphere.io"
  persistence:
    url: ""
    mode: "minio"
    region: "us-west-1" # region for s3

  tolerations:
  - key: "node-type"
    operator: "Equal"
    value: "hydrosphere.io"
    effect: "NoSchedule"
