ui:
  image:
    full: hydrosphere/hydro-serving-ui:21d6e940f310a36223bd6c51aac1d3c5fb7793ed
manager:
  image:
    full: hydrosphere/serving-manager:dab78c676ad4a82327a4ac9b24906583d20180bc
  depconfig: |-
    default-deployment-configuration = """
      {
        "name":"default",
        "hpa":{
            "minReplicas":1,
            "maxReplicas":10,
            "cpuUtilization":80
        },
        "pod":{
          "tolerations":[{
                "key":"node-type",
                "operator":"Equal",
                "value":"dev",
                "effect":"NoSchedule"
          }]
        }
      }
    """
gateway:
  image:
    full: hydrosphere/serving-gateway:baf1199aee714385e635dbfaee49e58954048da3
sonar:
  image:
    full: hydrosphere/sonar:495830e0910b65420c79e307d3b9df7f1a87917b
visualization:
  image:
    full: hydrosphere/hydro-visualization:b498e987681e5b8c71e7e9e0fe687e1d8673b50c
auto-od:
  image:
    full: hydrosphere/auto-od:d9b5700c61844a9748da1d847518e6de367a0309
stat:
  image:
    full: hydrosphere/stat:5b5bc87c010abbd0787b234c3e195564ce31c6b6
rootcause:
  image:
    full: hydrosphere/hydro-root-cause:b25c6c1e06934f5058f3526e4cc5f90c57ff625d
postgresql:
  metrics:
    enabled: true
  serviceMonitor:
    enabled: true
global:
  ui:
    ingress:
      enabled: true
      host: "hydro-serving.dev.hydrosphere.io"
      grpchost: "hydro-grpc.dev.hydrosphere.io"
  registry:
    insecure: false
    ingress:
      enabled: true
      host: "hydro-registry.dev.hydrosphere.io"
  persistence:
    url: ""
    mode: "minio"
    region: "us-west-1" # region for s3

  tolerations:
  - key: "node-type"
    operator: "Equal"
    value: "hydrosphere.io"
    effect: "NoSchedule"