ui:
  image:
    full: hydrosphere/hydro-serving-ui:5d55e1a62f1911d6329d139c0584e179691d0402
manager:
  image:
    full: hydrosphere/serving-manager:0f90ed836cc65203ebed399cad48d28c6139d2e0
  depconfig: |-
    default-deployment-configuration = """
      {
        "name":"default",
        "hpa":{
            "minReplicas":1,
            "maxReplicas":10,
            "cpuUtilization":80
        },
        "pod":{
          "tolerations":[{
                "key":"node-type",
                "operator":"Equal",
                "value":"hydrosphere.io",
                "effect":"NoSchedule"
          }]
        }
      }
    """
gateway:
  image:
    full: bulbawarrior/serving-gateway:9c1cba6ceeasdc844e8e3cd694f4724c29dsadasgs8f7c77e5
sonar:
  image:
    full: hydrosphere/sonar:495830e0910b65420c79e307d3b9df7f1a87917b
visualization:
  image:
    full: hydrosphere/hydro-visualization:94f27b119de749cc646d9faa3bedb83160d25002
auto-od:
  image:
    full: hydrosphere/auto-od:d9b5700c61844a9748da1d847518e6de367a0309
stat:
  image:
    full: hydrosphere/stat:5b5bc87c010abbd0787b234c3e195564ce31c6b6
rootcause:
  image:
    full: hydrosphere/hydro-root-cause:1d3495440b803fee80cdaa20707ae1d84a3796c7
global:
  tolerations:
  - key: "node-type"
    operator: "Equal"
    value: "hydrosphere.io"
    effect: "NoSchedule"