{{- if eq .Values.global.alertmanager.url ""}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "alertmanager.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "alertmanager.name" . }}
    chart: {{ include "alertmanager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "alertmanager.name" . }}
    release: {{ .Release.Name }}
{{- end }}