name: Global Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: manual version
        required: true
        
      skip_grpc:
        description: skip grpc? (yes|no)
        default: 'no'
        required: true
        
      skip_sdk: 
        description: skip sdk? (yes|no)
        default: 'no'
        required: true
env:
  DOCKER_REGISTRY_URL: bulbawarrior
  
jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - name: Release hydro-serving-protos
        if: github.event.inputs.skip_grpc == 'no'
        uses: aurelien-baudet/workflow-dispatch@v2.1.1
        with:
          workflow: cd
          token: ${{ secrets.HYDRO_SERVING_TOKEN }}
          repo: ${{ github.repository_owner }}/hydro-serving-protos
          inputs: '{"version":"${{ github.event.inputs.version }}"}'
          
      - name: Release hydro-serving-sdk
        if: github.event.inputs.skip_sdk == 'no'
        uses: aurelien-baudet/workflow-dispatch@v2.1.1
        with:
          workflow: cd
          token: ${{ secrets.HYDRO_SERVING_TOKEN }}
          repo: ${{ github.repository_owner }}/hydro-serving-sdk
          inputs: '{"version":"${{ github.event.inputs.version }}"}'

  Release_services:
    # template to release the rest of the repos
    runs-on: ubuntu-latest
    needs: [deps]
    strategy:
      matrix:
        service_repo_name: [hydro-serving-gateway] # repositories to release
    steps:
      - name: Release latest version of ${{ matrix.service_repo_name }}
        uses: aurelien-baudet/workflow-dispatch@v2.1.1
        with:
          workflow: cd
          token: ${{ secrets.HYDRO_SERVING_TOKEN }}
          repo: ${{ github.repository_owner }}/${{ matrix.service_repo_name }}
          inputs: '{"version":"${{ github.event.inputs.version }}"}'
       
  Bump_images:
    needs: [Release_services]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - env:
          IMAGE: serving-gateway
        name: Bump ${{ env.IMAGE }} version in chart
        uses: ./.github/actions/release-action
        with:
          release: global
          registry_url: ${{ env.DOCKER_REGISTRY_URL }}
          service_image_name: ${{ env.IMAGE }}
          tag: ${{ github.event.inputs.version }}
          
      - env:
          IMAGE: serving-manager
        name: Bump ${{ env.IMAGE }} version in chart
        uses: ./.github/actions/release-action
        with:
          release: global
          registry_url: ${{ env.DOCKER_REGISTRY_URL }}
          service_image_name: ${{ env.IMAGE }}
          tag: ${{ github.event.inputs.version }}
          
      - env:
          IMAGE: hydro-root-cause
        name: Bump ${{ env.IMAGE }} version in chart
        uses: ./.github/actions/release-action
        with:
          release: global
          registry_url: ${{ env.DOCKER_REGISTRY_URL }}
          service_image_name: ${{ env.IMAGE }}
          tag: ${{ github.event.inputs.version }}
      
      - env:
          IMAGE: sonar
        name: Bump ${{ env.IMAGE }} version in chart
        uses: ./.github/actions/release-action
        with:
          release: global
          registry_url: ${{ env.DOCKER_REGISTRY_URL }}
          service_image_name: ${{ env.IMAGE }}
          tag: ${{ github.event.inputs.version }}
        
      - env:
          IMAGE: stat
        name: Bump ${{ env.IMAGE }} version in chart
        uses: ./.github/actions/release-action
        with:
          release: global
          registry_url: ${{ env.DOCKER_REGISTRY_URL }}
          service_image_name: ${{ env.IMAGE }}
          tag: ${{ github.event.inputs.version }}
      
      - env:
          IMAGE: hydro-serving-ui
        name: Bump ${{ env.IMAGE }} version in chart
        uses: ./.github/actions/release-action
        with:
          release: global
          registry_url: ${{ env.DOCKER_REGISTRY_URL }}
          service_image_name: ${{ env.IMAGE }}
          tag: ${{ github.event.inputs.version }}
          
      - env:
          IMAGE: hydro-visualization
        name: Bump ${{ env.IMAGE }} version in chart
        uses: ./.github/actions/release-action
        with:
          release: global
          registry_url: ${{ env.DOCKER_REGISTRY_URL }}
          service_image_name: ${{ env.IMAGE }}
          tag: ${{ github.event.inputs.version }}
          
      - name: Setup helm
        uses: Azure/setup-helm@v1
        with:
          version: 2
      
      - name: Create helm release
        run: |
          cd helm
          helm init --client-only --stable-repo-url https://charts.helm.sh/stable
          helm package --dependency-update --version ${{ github.event.inputs.version }} serving
          
      - name: Calculate release sha
        id: sha
        run: |
          cd helm
          SHA=$(shasum -a 256 -b ./serving-3.0.0.tgz | awk '{ print $1 }')
          echo ::set-output name=sha::$SHA
          
      - name: Update readme.md
        env:
          sedCommand: 's/[0-9]+\.[0-9]+\.[0-9]+\/serving-[0-9]+\.[0-9]+\.[0-9]+\.tgz/${{ github.event.inputs.version }}\/serving-${{ github.event.inputs.version }}.tgz/g'
        run: |
          echo $sedCommand
          cd helm
          sed -i 'README.md' -E -e $sedCommand README.md
          
      - name: Add release metadata
        run: |
          cd helm
          ./add_version.sh ${{ github.event.inputs.version }} ${{ steps.sha.outputs.sha }}
          
      - name: Push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Releasing global version ${{ github.event.inputs.version }}" -a
          git push
