name: Global Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: manual version
        required: true
        
env:
  DOCKER_REGISTRY_URL: bulbawarrior
  
jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - name: Release hydro-serving-protos
        uses: aurelien-baudet/workflow-dispatch@v2.1.1
        with:
          workflow: cd
          token: ${{ secrets.HYDRO_SERVING_TOKEN }}
          repo: ${{ github.repository_owner }}/hydro-serving-protos
          inputs: '{"version":"${{ github.event.inputs.version }}"}'
          
      - name: Release hydro-serving-sdk
        uses: aurelien-baudet/workflow-dispatch@v2.1.1
        with:
          workflow: cd
          token: ${{ secrets.HYDRO_SERVING_TOKEN }}
          repo: ${{ github.repository_owner }}/hydro-serving-sdk
          inputs: '{"version":"${{ github.event.inputs.version }}"}'

  Release_services:
    # template to release the rest of the repos
    runs-on: ubuntu-latest
    needs: [deps]
    strategy:
      matrix:
        service_repo_name: [hydro-serving-gateway] # repositories to release
    steps:
      - name: Release latest version of ${{ matrix.service_repo_name }}
        uses: aurelien-baudet/workflow-dispatch@v2.1.1
        with:
          workflow: cd
          token: ${{ secrets.HYDRO_SERVING_TOKEN }}
          repo: ${{ github.repository_owner }}/${{ matrix.service_repo_name }}
          inputs: '{"version":"${{ github.event.inputs.version }}"}'
       
  Bump_images:
    needs: [Release_services]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service_image_name: [serving-gateway] # names of docker images to be updated TODO: get image names as outputs from release runs
    concurrency: 1 # avoid race conditions
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Update ${{ matrix.service_image_name }} version
        uses: ./.github/actions/release-action
        with:
          release: global
          registry_url: ${{ env.DOCKER_REGISTRY_URL }}
          service_image_name: ${{ matrix.service_image_name }}
          tag: ${{ github.event.inputs.version }}
          
    
