name: Global Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: manual version
        required: true
        
env:
  DOCKER_REGISTRY_URL: bulbawarrior
  
jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - name: Release hydro-serving-protos
        uses: aurelien-baudet/workflow-dispatch@v2.1.1
        with:
          workflow: cd
          token: ${{ secrets.HYDRO_SERVING_TOKEN }}
          repo: ${{ github.repository_owner }}/hydro-serving-protos
          inputs: '{"version":"${{ github.event.inputs.version }}"}'
          
      - name: Release hydro-serving-sdk
        uses: aurelien-baudet/workflow-dispatch@v2.1.1
        with:
          workflow: cd
          token: ${{ secrets.HYDRO_SERVING_TOKEN }}
          repo: ${{ github.repository_owner }}/hydro-serving-sdk
          inputs: '{"version":"${{ github.event.inputs.version }}"}'

  Release_services:
    # template to release the rest of the repos
    runs-on: ubuntu-latest
    needs: [deps]
    strategy:
      matrix:
        service_repo_name: [hydro-serving-gateway] # repositories to release
    steps:
      - name: Release latest version of ${{ matrix.service_repo_name }}
        uses: aurelien-baudet/workflow-dispatch@v2.1.1
        with:
          workflow: cd
          token: ${{ secrets.HYDRO_SERVING_TOKEN }}
          repo: ${{ github.repository_owner }}/${{ matrix.service_repo_name }}
          inputs: '{"version":"${{ github.event.inputs.version }}"}'
       
  Bump_images:
    needs: [Release_services]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - env:
          IMAGE: serving-gateway
        name: Bump ${{ env.IMAGE }} version in chart
        uses: ./.github/actions/release-action
        with:
          release: global
          registry_url: ${{ env.DOCKER_REGISTRY_URL }}
          service_image_name: ${{ env.IMAGE }}
          tag: ${{ github.event.inputs.version }}
          
      - env:
          IMAGE: serving-manager
        name: Bump ${{ env.IMAGE }} version in chart
        uses: ./.github/actions/release-action
        with:
          release: global
          registry_url: ${{ env.DOCKER_REGISTRY_URL }}
          service_image_name: ${{ env.IMAGE }}
          tag: ${{ github.event.inputs.version }}
          
      - env:
          IMAGE: hydro-root-cause
        name: Bump ${{ env.IMAGE }} version in chart
        uses: ./.github/actions/release-action
        with:
          release: global
          registry_url: ${{ env.DOCKER_REGISTRY_URL }}
          service_image_name: ${{ env.IMAGE }}
          tag: ${{ github.event.inputs.version }}
      
      - env:
          IMAGE: sonar
        name: Bump ${{ env.IMAGE }} version in chart
        uses: ./.github/actions/release-action
        with:
          release: global
          registry_url: ${{ env.DOCKER_REGISTRY_URL }}
          service_image_name: ${{ env.IMAGE }}
          tag: ${{ github.event.inputs.version }}
        
      - env:
          IMAGE: stat
        name: Bump ${{ env.IMAGE }} version in chart
        uses: ./.github/actions/release-action
        with:
          release: global
          registry_url: ${{ env.DOCKER_REGISTRY_URL }}
          service_image_name: ${{ env.IMAGE }}
          tag: ${{ github.event.inputs.version }}
      
      - env:
          IMAGE: hydro-serving-ui
        name: Bump ${{ env.IMAGE }} version in chart
        uses: ./.github/actions/release-action
        with:
          release: global
          registry_url: ${{ env.DOCKER_REGISTRY_URL }}
          service_image_name: ${{ env.IMAGE }}
          tag: ${{ github.event.inputs.version }}
          
      - env:
          IMAGE: hydro-visualization
        name: Bump ${{ env.IMAGE }} version in chart
        uses: ./.github/actions/release-action
        with:
          release: global
          registry_url: ${{ env.DOCKER_REGISTRY_URL }}
          service_image_name: ${{ env.IMAGE }}
          tag: ${{ github.event.inputs.version }}
          
      - name: Push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Releasing global version ${{ github.event.inputs.version }}" -a
          git push
