name: Local release
on:
  workflow_dispatch:
    inputs:
      service_image_name:
        description: the service image to be updated
        required: true
        
      registry_url:
        required: true
        
      tag:
        description: version tag of the image
        required: true

jobs:

  Update:
    runs-on: ubuntu-latest
    
    name: Bump image tag
    env:
      IMAGE_NAME: ${{ github.event.inputs.service_image_name }}
      REGISTRY_URL: ${{ github.event.inputs.registry_url }}
      TAG: ${{ github.event.inputs.tag }}
      
    steps:
      - name: Set HELM_CHART_NAME
        run: |
          case $IMAGE_NAME in
          
            serving-gateway)
              HELM_CHART_NAME=gateway
              ;;
              
            serving-manager)
              HELM_CHART_NAME=manager
              ;;
              
            hydro-root-cause)
              HELM_CHART_NAME=rootcause
              ;;
              
            sonar)
              HELM_CHART_NAME=sonar
              ;;
              
            stat)
              HELM_CHART_NAME=stat
              ;;
              
            hydro-serving-ui)
              HELM_CHART_NAME=ui
              ;;  
            
            hydro-visualization)
              HELM_CHART_NAME=visualization
              ;;
            
            *)
              echo "unknown IMAGE_NAME"
              exit 1
              ;;
          esac
          
          echo HELM_CHART_NAME=$HELM_CHART_NAME >> $GITHUB_ENV
          
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
        
      - name: Update ${{env.HELM_CHART_NAME}}/values.yaml
        run: "cd helm && sed -i \"s/.*full:.*/  full: $REGISTRY_URL\\/$IMAGE_NAME:$TAG/g\" $HELM_CHART_NAME/values.yaml"
      
      - name: Update dev.yaml
        run: "cd helm && sed -i \"s/.*$IMAGE_NAME.*/    full: $REGISTRY_URL\\/$IMAGE_NAME:$TAG/g\" dev.yaml"
        
        # frigate needs installation
        
        
      - name: Push to repo
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "bump $IMAGE_NAME version in dev.yaml" -a
          git push
